### ISSUE TITLE
What attributes can you change

### ISSUE THREAD

**Issue by JetpackRescue** [CorgiTaco-Archive/Mobifier#3]
in the new documentation for 1.1 you didn't list all of the attributes you can change. The new config didn't populate with every mob like the last version, instead it populated with only the husk. When it populated, why do the numbers have a asterisk in front of them? does that mean times 2? in the last version no asterisk was needed? Why did it auto populate the husk with *2 of everything when it should have populated with *1. does *2 mean the default amount minecraft sets? 

The documentation is severely lacking with examples. 

In the "has equipped item" condition, where are you getting the "durability_is" and "enchantment_check" from? Where can I find what else is available to be checked? 

There's no discord server, the comments are turned off, and the documentation doesn't explain a lot, so i'm posting this here.

**Comment by CorgiTaco** [comment]
The attributes that can be changed cannot really be listed bc mods may add custom ones. Yes * is multiplication. And the husk was used as a sort of example

**Comment by CorgiTaco** [comment]
Also here's a discord invite: https://discord.gg/eBDpRVtsmJ

**Comment by NighthowlerStudios** [comment]
the attributes that your modpack will allow you to change will be put into the default config the mod will generate on world start.  use that as reference.

**Comment by CorgiTaco** [comment]
In the latest release, if you add `dump_registries` to your config and mark it as `true` it will dump all the information from the registries including attributes. See [here](https://github.com/CorgiTaco/Mobifier/wiki/Config-Structure) to see where it should be in your config.
