### ISSUE TITLE
[Crash]: Malum Damage Type Conflict

### ISSUE THREAD

**Issue by Legomastar** [CorgiTaco-Archive/Mobifier#7]
### Minecraft Version

1.18.2

### Mobifier Version

1.0.2

### Mod Loader

Forge

### Mod Loader Version

40.1.16

### What happened?

Minecraft crashed on trying to load a world, not enough crashes suggested mobifier as suspect.
The error stops when I downgrade malum to 1.3.4, changing mobifier version had no effect.
The first error in the crash log is:

> java.lang.IllegalArgumentException: "malum:magic_damage" is not a valid id in registry: Registry[ResourceKey[minecraft:root / minecraft:attribute] (Experimental)].

### crash-log

[crash-2022-05-13_07.43.09-client.txt](https://github.com/CorgiTaco/Mobifier/files/8686738/crash-2022-05-13_07.43.09-client.txt)

### latest.log

[latest.log](https://github.com/CorgiTaco/Mobifier/files/8686733/latest.log)

**Comment by CorgiTaco** [comment]
Looks like either the the ID changed or it was removed altogether, look in the registry dump file to see the available IDs in the attributes registry.

**Comment by CorgiTaco** [comment]
To have the registry dump file generate make "dump_registries": true
